# Generated by Django 2.0.4 on 2018-05-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_id',
            field=models.CharField(max_length=20, verbose_name='REFERENCIA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='IVA'),
        ),
    ]
