# Generated by Django 2.0.4 on 2018-06-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180609_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fabricante',
            unique_together={('slug', 'parent')},
        ),
    ]
