# Generated by Django 2.0.6 on 2018-06-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180630_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ref',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
