# Generated by Django 2.0.4 on 2018-05-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180508_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='public_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='REFERENCIA'),
        ),
    ]
