# Generated by Django 2.0.4 on 2018-05-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180510_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='src',
            field=models.URLField(unique=True),
        ),
    ]
