# Generated by Django 2.0.4 on 2018-05-08 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180508_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='public_id',
        ),
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, primary_key=True, serialize=False, verbose_name='Referencia'),
            preserve_default=False,
        ),
    ]
