# Generated by Django 2.0.6 on 2018-07-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180701_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ('name',), 'verbose_name': 'Fabricante', 'verbose_name_plural': 'Marcas'},
        ),
    ]
