# Generated by Django 2.0.4 on 2018-05-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180510_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='ref',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='src',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
