# Generated by Django 2.0.4 on 2018-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180508_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ref',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
