# Generated by Django 2.0.4 on 2018-05-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180523_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
