# Generated by Django 2.0.4 on 2018-05-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180508_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
