# Generated by Django 2.0.4 on 2018-05-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180525_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=None, related_name='children', to='shop.Fabricante'),
        ),
    ]
