# Generated by Django 2.0.4 on 2018-05-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180508_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ref',
            field=models.CharField(max_length=20, unique=True, verbose_name='Referencia'),
        ),
    ]
