# Generated by Django 2.0.4 on 2018-05-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_fabricante_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='externo',
            name='n_fabricantes',
            field=models.IntegerField(default=0),
        ),
    ]
