# Generated by Django 2.0.4 on 2018-05-18 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_externo_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
    ]
