# Generated by Django 2.0.4 on 2018-05-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_externo_n_fabricantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated',)},
        ),
    ]
