# Generated by Django 2.0.4 on 2018-06-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20180626_1925'),
    ]

    operations = [
    ]
