# Generated by Django 2.0.4 on 2018-05-25 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180525_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ('name',), 'verbose_name_plural': 'fabricantes'},
        ),
        migrations.AddField(
            model_name='fabricante',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Imagen_gen'),
        ),
        migrations.AlterField(
            model_name='imagen_gen',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
