# Generated by Django 2.0.4 on 2018-05-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180508_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='product_id',
        ),
    ]
