# Generated by Django 2.0.4 on 2018-05-19 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180518_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 19, 3, 13, 57, 693567), verbose_name='Última Actualización'),
        ),
    ]
