# Generated by Django 2.0.4 on 2018-05-19 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20180519_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='externo',
            name='n_imagenes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='externo',
            name='n_productos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 19, 3, 37, 48, 69102), verbose_name='Última Actualización'),
        ),
    ]
