# Generated by Django 2.0.4 on 2018-05-28 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20180528_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='portada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Imagen_gen'),
        ),
    ]
