# Generated by Django 2.0.4 on 2018-05-30 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_portada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-release_date',)},
        ),
    ]
