# Generated by Django 2.0.4 on 2018-05-31 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20180530_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabricante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Fabricante'),
        ),
    ]
