# Generated by Django 2.0.4 on 2018-05-19 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20180519_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externo',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 19, 13, 44, 31, 551885), verbose_name='Última Actualización'),
        ),
    ]
