# Generated by Django 2.0.4 on 2018-05-20 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20180520_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 20, 23, 18, 26, 447766), verbose_name='Última Actualización'),
        ),
    ]
