# Generated by Django 2.0.4 on 2018-05-21 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20180520_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 21, 1, 27, 21, 335195), verbose_name='Última Actualización'),
        ),
    ]
