# Generated by Django 2.0.4 on 2018-05-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
