# Generated by Django 2.0.4 on 2018-05-23 17:28

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20180523_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='J:\\salvar\\ServidorWamp\\python\\djangogirls\\static/img'), upload_to='')),
                ('url', models.URLField(null=True)),
                ('preferred', models.BooleanField(default=False, verbose_name='Portada')),
            ],
        ),
        migrations.AddField(
            model_name='externo',
            name='n_categorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Image'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='preferred',
            field=models.BooleanField(default=False, verbose_name='Portada'),
        ),
    ]
