# Generated by Django 2.0.4 on 2018-05-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20180523_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(null=True, unique=True),
        ),
    ]
