# Generated by Django 2.0.4 on 2018-05-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20180523_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Imagen_gen',
        ),
    ]
