# Generated by Django 2.0.4 on 2018-05-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20180523_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='gesioid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
