# Generated by Django 2.0.4 on 2018-06-09 12:15

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=200, unique=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='J:\\salvar\\ServidorWamp\\python\\djangogirls\\static/store'), upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='Última Actualización')),
                ('n_productos', models.IntegerField(default=0)),
                ('n_fabricantes', models.IntegerField(default=0)),
                ('n_imagenes', models.IntegerField(default=0)),
                ('n_categorias', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Marcas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('ref', models.CharField(blank=True, max_length=20)),
                ('src', models.URLField(unique=True)),
                ('url', models.URLField(blank=True)),
                ('preferred', models.BooleanField(default=False, verbose_name='Portada')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen_gen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='J:\\salvar\\ServidorWamp\\python\\djangogirls\\static/img'), upload_to='')),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('preferred', models.BooleanField(default=False, verbose_name='Portada')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('title', models.CharField(max_length=200)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_url', models.URLField(blank=True)),
                ('recommended_retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('default_shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('delivery_desc', models.CharField(blank=True, max_length=20)),
                ('vat', models.DecimalField(decimal_places=2, default=21.0, max_digits=4, verbose_name='IVA')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Lanzamiento')),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Fabricante')),
                ('portada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Imagen_gen')),
            ],
            options={
                'ordering': ('-release_date',),
            },
        ),
        migrations.AddField(
            model_name='imagen',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Imagen_gen'),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Fabricante'),
        ),
        migrations.AlterUniqueTogether(
            name='fabricante',
            unique_together={('slug', 'parent')},
        ),
    ]
