# Generated by Django 2.0.4 on 2018-05-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recommended_retail_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('default_shipping_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name=21.0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('html_description', models.TextField()),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('destocking', models.BooleanField()),
                ('brand', models.CharField(max_length=200)),
                ('brand_hierarchy', models.TextField()),
                ('shipping_weight_grame', models.IntegerField()),
            ],
        ),
    ]
