# Generated by Django 2.1 on 2018-08-07 13:22

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('activo', models.BooleanField(default=True)),
                ('gesioid', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorias',
                'ordering': ('parent', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=200, unique=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField()),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\salvar\\xampp\\htdocs\\djangogirls\\static/store'), upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='Última Actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('ref', models.CharField(max_length=20, null=True)),
                ('src', models.URLField(unique=True)),
                ('img', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\salvar\\xampp\\htdocs\\djangogirls\\static/img'), upload_to='')),
                ('preferred', models.BooleanField(default=False, verbose_name='Portada')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_description', models.TextField(blank=True, null=True)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Lanzamiento')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('destocking', models.BooleanField(default=False, verbose_name='Liquidación')),
                ('sale', models.BooleanField(default=False, verbose_name='Rebajado')),
                ('new', models.BooleanField(default=True, verbose_name='Nuevo')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recommended_retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('default_shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('delivery_desc', models.CharField(blank=True, max_length=20)),
                ('vat', models.DecimalField(decimal_places=2, default=21.0, max_digits=4, verbose_name='IVA')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=20)),
                ('pvp', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(to='shop.Category')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_ppal', to='shop.Category')),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabricante', to='shop.Category')),
                ('imagens', models.ManyToManyField(to='shop.Imagen')),
            ],
            options={
                'ordering': ('-release_date',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Imagen'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
    ]
