# Generated by Django 2.0.4 on 2018-06-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
