# Generated by Django 2.0.4 on 2018-05-23 21:13

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('gesioid', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=200)),
                ('valor', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='J:\\salvar\\ServidorWamp\\python\\djangogirls\\static/store'), upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='Última Actualización')),
                ('n_productos', models.IntegerField(default=0)),
                ('n_imagenes', models.IntegerField(default=0)),
                ('n_categorias', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen_gen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='J:\\salvar\\ServidorWamp\\python\\djangogirls\\static/img'), upload_to='')),
                ('url', models.URLField(null=True, unique=True)),
                ('preferred', models.BooleanField(default=False, verbose_name='Portada')),
            ],
        ),
        migrations.AddField(
            model_name='imagen',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagen',
            name='ref',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='default_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_desc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='html_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lanzamiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=4, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='preferred',
            field=models.BooleanField(default=False, verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='src',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Imagen_gen'),
        ),
    ]
