# Generated by Django 2.0.4 on 2018-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='ref',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
