# Generated by Django 2.0.4 on 2018-05-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180507_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_hierarchy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_shipping_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='destocking',
        ),
        migrations.RemoveField(
            model_name='product',
            name='html_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_weight_grame',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vat',
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
