# Generated by Django 2.0.4 on 2018-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180609_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='fabricante',
            unique_together={('name', 'slug', 'parent')},
        ),
    ]
