# Generated by Django 2.0.4 on 2018-05-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180523_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'categorias'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='children', to='shop.Categoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='categorias',
            field=models.ManyToManyField(to='shop.Categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
