# Generated by Django 2.0.4 on 2018-05-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180510_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='src',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
