# Generated by Django 2.0.4 on 2018-06-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180609_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='destocking',
            field=models.BooleanField(default=False, verbose_name='Liquidación'),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Nuevo'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Rebajado'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
