# Generated by Django 2.0.6 on 2018-07-01 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180701_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='portada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Imagen_gen'),
        ),
    ]
