# Generated by Django 2.0.4 on 2018-05-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180510_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='default_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_desc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='destocking',
            field=models.BooleanField(default=False, verbose_name='Liquidación'),
        ),
        migrations.AddField(
            model_name='product',
            name='html_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Nuevo'),
        ),
        migrations.AddField(
            model_name='product',
            name='prepaid_reservation',
            field=models.BooleanField(default=False, verbose_name='Pre-Pedido'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lanzamiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Rebajado'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_weight_grame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=4, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='preferred',
            field=models.BooleanField(verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
