# Generated by Django 2.0.4 on 2018-06-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180615_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
