# Generated by Django 2.0.4 on 2018-05-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180511_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_shipping_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='destocking',
        ),
        migrations.RemoveField(
            model_name='product',
            name='html_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prepaid_reservation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recommended_retail_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_weight_grame',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_of_measurement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vat',
        ),
    ]
