# Generated by Django 2.0.6 on 2018-07-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180702_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ('name',), 'verbose_name': 'Fabricante', 'verbose_name_plural': 'Fabricantes y Marcas'},
        ),
    ]
