# Generated by Django 2.0.4 on 2018-05-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180525_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorias',
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='shop.Categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('slug', 'parent')},
        ),
    ]
