# Generated by Django 2.0.6 on 2018-07-04 02:22

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180703_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externo',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\salvar\\djangogirls\\static/store'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='imagen_gen',
            name='img',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\salvar\\djangogirls\\static/img'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabricante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabricante', to='shop.Fabricante'),
        ),
    ]
