# Generated by Django 2.0.4 on 2018-05-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180511_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
