# Generated by Django 2.0.4 on 2018-05-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180525_1304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
