# Generated by Django 2.0.4 on 2018-05-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_recommended_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
