# Generated by Django 2.0.6 on 2018-07-11 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180704_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='portada',
        ),
    ]
