# Generated by Django 2.0.4 on 2018-05-14 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180514_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='externo',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización'),
        ),
    ]
