# Generated by Django 2.0.4 on 2018-05-18 12:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180518_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externo',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/store/'), upload_to=''),
        ),
    ]
