# Generated by Django 2.0.4 on 2018-05-25 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20180525_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.Fabricante'),
        ),
    ]
