# Generated by Django 2.0.4 on 2018-05-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20180525_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ('name',), 'verbose_name': 'fabricantes', 'verbose_name_plural': 'marcas'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
    ]
