# Generated by Django 2.0.4 on 2018-05-19 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20180519_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 19, 4, 12, 53, 451113), verbose_name='Última Actualización'),
        ),
    ]
