# Generated by Django 2.0.4 on 2018-05-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20180531_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='src',
            field=models.URLField(unique=True),
        ),
    ]
